// import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap-icons/font/bootstrap-icons.css'
import Navbar from "./components/Navbar";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import { ClerkProvider } from "@clerk/nextjs";
import ThemeProvider from "@/Context";
// import ThemeProvider from "@/Context";

// const inter = Inter({ subsets: ["latin"] });

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata = {
  title: "AI Flash Card",
  description: "Generated by DEVENGERS",
};

export default function RootLayout({ children }) {
  return (
      <ClerkProvider>

        <html lang="en" className="bg-indigo-950">
          <body  className={cn("min-h-screen bg-background font-sans antialiased",)}>
            <ThemeProvider>
              <Navbar/>
              {children}
            </ThemeProvider>
          </body>
        </html>
      </ClerkProvider>
  );
}
